# Generated by Django 5.1.2 on 2024-11-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='data',
            new_name='Song',
        ),
    ]
